"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 16:18:31.362723
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('methodology', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('default_time_unit', sa.String(length=10), nullable=False),
    sa.Column('default_task_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('default_sprint_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('minutes_per_day', sa.Integer(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('days_per_month', sa.Integer(), nullable=False),
    sa.Column('calendar_week', sa.JSON(), nullable=False),
    sa.Column('schedule_start', sa.DateTime(), nullable=True),
    sa.Column('schedule_finish', sa.DateTime(), nullable=True),
    sa.Column('schedule_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('schedule_std_dev_minutes', sa.Float(), nullable=True),
    sa.Column('schedule_target_probability', sa.Float(), nullable=True),
    sa.Column('schedule_critical_ids', sa.JSON(), nullable=True),
    sa.Column('schedule_warnings', sa.JSON(), nullable=True),
    sa.Column('schedule_calculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_exceptions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('intervals', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'day')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_role_name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_project_id'), ['project_id'], unique=False)

    op.create_table('work_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('duration_unit', sa.String(length=10), nullable=False),
    sa.Column('estimation_mode', sa.String(length=10), nullable=False),
    sa.Column('pert_optimistic', sa.Float(), nullable=True),
    sa.Column('pert_most_likely', sa.Float(), nullable=True),
    sa.Column('pert_pessimistic', sa.Float(), nullable=True),
    sa.Column('constraint_type', sa.String(length=10), nullable=False),
    sa.Column('constraint_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('early_start', sa.Integer(), nullable=True),
    sa.Column('early_finish', sa.Integer(), nullable=True),
    sa.Column('late_start', sa.Integer(), nullable=True),
    sa.Column('late_finish', sa.Integer(), nullable=True),
    sa.Column('total_float', sa.Integer(), nullable=True),
    sa.Column('free_float', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_finish', sa.DateTime(), nullable=True),
    sa.CheckConstraint('duration_minutes >= 0', name='ck_item_duration'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_item_progress'),
    sa.ForeignKeyConstraint(['parent_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_items_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_project_id'), ['project_id'], unique=False)

    op.create_table('dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('predecessor_id', sa.String(length=36), nullable=False),
    sa.Column('successor_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=2), nullable=False),
    sa.Column('lag_minutes', sa.Integer(), nullable=False),
    sa.Column('lag_unit', sa.String(length=10), nullable=False),
    sa.CheckConstraint('predecessor_id <> successor_id', name='ck_dependency_not_self'),
    sa.ForeignKeyConstraint(['predecessor_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', name='uq_dependency_pair')
    )
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependencies_project_id'), ['project_id'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('responsibility', sa.Text(), nullable=False),
    sa.Column('hours_per_day', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_project_id'), ['project_id'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'member_id', name='uq_assignment')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_project_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_project_id'))

    op.drop_table('members')
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependencies_project_id'))

    op.drop_table('dependencies')
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_parent_id'))

    op.drop_table('work_items')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_project_id'))

    op.drop_table('roles')
    op.drop_table('calendar_exceptions')
    op.drop_table('projects')
    # ### end Alembic commands ###
